export const enum VISTAS_EXALUMNO {
    INACAPMAIL = 'APP_EXA_CORREO',
    ENVIA_CORREO = 'APP_EXA_ENVIA_CORREO',
    CREDENCIAL = 'APP_EXA_CREDENCIAL',
    CONFIGURACIONES = 'APP_EXA_CONFIGURACIONES',
    PERFIL = 'APP_EXA_PERFIL',
    DATOS_PERSONALES = 'APP_EXA_DATOS_PERSONALES',
    FOTO_PERFIL = 'APP_EXA_FOTO_PERFIL',
    EMPLEA_INACAP = 'APP_EXA_EMPLEA_INACAP',
    DETALLE_EMPLEO = 'APP_EXA_DETALLE_EMPLEO',
    SEDE = 'APP_EXA_SEDE',
    SERVICIOS = 'APP_EXA_SERVICIOS',
    CERTIFICADOS = 'APP_EXA_CERTIFICADOS',
    SOLICITUDES = 'APP_EXA_SOLICITUDES',
    EMPRENDEDORES = 'APP_EXA_EMPRENDEDORES'
};