export const enum VISTAS {
    INICIO = 'APP_PUB_INICIO',
    DESTACADO = 'APP_PUB_DESTACADO',
    DETALLE_NOTICIA = 'APP_PUB_DETALLE_NOTICIA',

    INACAP = 'APP_PUB_INACAP',
    DETALLE_INACAP = 'APP_PUB_DETALLE_INACAP',
    INSTITUCIONES = 'APP_PUB_INSTITUCIONES',

    PROGRAMAS = 'APP_PUB_PROGRAMAS',
    DETALLE_CARRERA = 'APP_PUB_DETALLE_CARRERA',
    FUP = 'APP_PUB_FUP',
    MALLA_CURRICULAR = 'APP_PUB_MALLA',

    EDUC_CONTINUA = 'APP_PUB_EDUC_CONTINUA',
    DETALLE_CURSO = 'APP_PUB_DETALLE_CURSO',
    INSCRIPCION_CURSO = 'APP_PUB_INSCRIPCION_CURSO',
    PAGO_EXITOSO_CURSO = 'APP_PUB_PAGO_EXITOSO_CURSO',
    PAGO_FRACASO_CURSO = 'APP_PUB_PAGO_FRACASO_CURSO',

    SEDES = 'APP_PUB_SEDES',
    DETALLE_SEDE = 'APP_PUB_DETALLE_SEDE',
    OFERTA_SEDE = 'APP_PUB_OFERTA_SEDE',

    SERVICIOS = 'APP_PUB_SERVICIOS',
    CONSULTA_BIP = 'APP_PUB_CONSULTA_BIP',
    SERVICIOS_TECNOLOGICOS = 'APP_PUB_SERVICIOS_TECNOLOGICOS',
    VERIFICACION_DOCUMENTOS = 'APP_PUB_VERIFICACION_DOCUMENTOS',
    VERSION_APP = 'APP_PUB_VERSION_APP',

    NOTIFICACIONES = 'APP_PUB_NOTIFICACIONES',
    DETALLE_NOTIFICACION = 'APP_PUB_DETALLE_NOTIFICACION'
};